version: '3.8'
services:
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./src/main/resources/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
# to start :: D:\madeeasy.com\spring-boot-prometheus>docker-compose up -d
# to stop  :: D:\madeeasy.com\spring-boot-prometheus> docker-compose down
